
---

- hosts: localhost

  become: yes

  tasks:

    - name: Install Java

      apt:

        name: openjdk-8-jdk

        state: present

        update_cache: yes

    - name: Add Jenkins apt key

      apt_key:

        url: https://pkg.jenkins.io/debian/jenkins.io.key

        state: present

    - name: Add Jenkins apt repository

      apt_repository:

        repo: deb http://pkg.jenkins.io/debian-stable binary/

        state: present

    - name: Install Jenkins

      apt:

        name: jenkins

        state: present

        update_cache: yes

    - name: Start Jenkins

      service:

        name: jenkins

        state: started

        enabled: yes


